project_id = "cuanladihtpvkmjhvrln"

[functions.send-notification-email]
verify_jwt = false

[functions.check-budgets]
verify_jwt = false

[functions.send-monthly-reports]
verify_jwt = false

[functions.process-recurring-transactions]
verify_jwt = false
